### PR TITLE
Remove unnecessary conversion when sending loc

### PR DESCRIPTION
**Pull request by daijoubu**
This should fix the incorrect relative heading displayed in Inav.

### CODE REVIEW

**Comment by mmosca** [comment]
@daijoubu was this tested with successfully in INAV?

@MUSTARDTIGERFPV you may need to update your ardupilot build to match.

**Comment by daijoubu** [comment]
@mmosca I have built it but have not had a chance to fly it yet. I won't get that until this weekend.  Unfortunately my bench setup can't generate a consistent course over ground. If you're able to fly before me I'd appreciate the feedback.

**Comment by mmosca** [comment]
I am on the same boat. I see no reason to not merge this, once someone can confirm this fixes the arrows.

Good job debugging this one.

**Comment by daijoubu** [comment]
@mmosca @MUSTARDTIGERFPV I have tested this with Inav HITL to provide a peer in flight and confirmed that this change fixes the relative heading indicator behaviour.  Before the fix, the peers are broadcasting a course over ground that varies from 0-36.  After the fix, the peers broadcast a course over ground that varies from 0-360.  With my plane pointing N, the relative heading indicator points up when the HITL plane is flying North and the indicator points down when the HITL plane turns around to fly South.  The relative heading indicator varies as the HITL plane changes course.

**Review by MUSTARDTIGERFPV — APPROVED** [review]

**Pull request merged**
