### PR TITLE
Switch MSP_SET_GPS_RAW to MSP2_GPS_SENSOR message and add spoofing to

### PR DESCRIPTION
**Pull request by mmosca**
With this change FormationFlight will show up as a valid MSP gps sensor

FF is marked as a working msp gps unit in INAV:
image

FF is reporting a 3d fix with position data:
image

### CODE REVIEW

**Comment by MUSTARDTIGERFPV** [comment]
Approved workflow runs - I look forward to merging this when it's ready! :D

**Comment by mmosca** [comment]
Current status is a step forward from before, but It is still waiting for tesitng on my side. INAV recognizes the gnss injection, ardupilot didn't (could be me failing to set it up propperly).

There are few todos related to the fact the GNSSLocation does not have all the info needed for MSP2_GPS_SENSOR response.

**Comment by mmosca** [comment]
Probably a good stopping point for now. I don't have hardware with extra serial ports to connect to a gps unit. 

The next step would probably be to change GNSSLocation to add the missing fields needed for MSP2_GPS_SENSOR

**Comment by mmosca** [comment]
Don't merge yet, it looks like I might have broken the id selection.

**Comment by mmosca** [comment]
Reverted some changes and got id selection fixed.

image

Is the number of peers supposed to show 1 or 2 when there is 1 person flying with you?

**Comment by mmosca** [comment]
And peer spoofing:
image

**Comment by mmosca** [comment]
Confirmed healthy gps in AP, and spoofed position on map.

image

image

**Pull request merged**
